name: smart_home
description: test smart home app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10


dependencies:
  auth_api:
    path: packages/auth_api
  auth_local_storage:
    path: packages/auth_local_storage
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.0
  devices_api:
    path: packages/devices_api
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  google_fonts: ^4.0.2
  home_api:
    path: packages/home_api
  home_repository:
    path: packages/home_repository
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  lights_api:
    path: packages/lights_api
  lights_repository:
    path: packages/lights_repository
  mqtt_smarthome_client:
    path: packages/mqtt_smarthome_client
  path_provider: ^2.0.14
  room_api:
    path: packages/room_api
  room_repository:
    path: packages/room_repository
  rxdart: ^0.27.7
  smart_home_api_client:
    path: packages/smart_home_api_client

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/home_banner.png



